[Launch]
# Nombre que aparecerá en la cabecera del proceso
Name=dev_console_portable
# El ejecutable real que debe lanzar (relativo a la carpeta App)
ProgramExecutable=Git\bin\bash.exe
# Argumentos para que inicie como consola interactiva
CommandLineArguments=--login -i
# Directorio de inicio predeterminado
WorkingDirectory=%PAL:DataDir%\home

[Environment]
# Definición del HOME en la carpeta de datos persistentes
HOME=%PAL:DataDir%\home
# Construcción del PATH portable
PATH=%PAL:AppDir%\uv;%PAL:AppDir%\NodeJS;%PAL:AppDir%\Git\bin;%PAL:AppDir%\Git\usr\bin;%PATH%

[Details]
# Estos datos deben coincidir exactamente con tu appinfo.ini
AppID=dev_console_portable
Name=dev_console_portable